[variables]
NIXPACKS_NO_CACHE = '1'

[phases.setup]
nixPkgs = ['ruby']

[phases.build]
cmds = [
  'bundle install --deployment --without development test'
]

[start]
cmd = 'bundle exec rails server -b 0.0.0.0 -p $PORT'