[build]
builder = "nixpacks"

[deploy]
# Disable health check temporarily
# healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
RAILS_ENV = "production"